#!/bin/bash
# ~/hexbox/setup/configure.sh
# One-command configuration: sets attacker IP, credentials, and interface names
# across all files. Run this once after cloning the repo or after changing
# your deployment environment.

set -euo pipefail

HEXBOX_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG="$HEXBOX_DIR/config.json"
PAYLOADS="$HEXBOX_DIR/payloads"

echo "╔══════════════════════════════════════════════╗"
echo "║       HexBox — One-Time Configuration        ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "  Leave any field blank to keep the default shown in [brackets]."
echo ""

# ---- Network / IP settings ----
read -rp "[?] HexBox / attacker IP          [10.0.0.99]:       " HEXBOX_IP
read -rp "[?] Default scan target subnet    [192.168.1.0/24]:  " SCAN_NET
read -rp "[?] C2 external server IP         [YOUR.C2.IP.HERE]: " C2_IP

echo ""
echo "  Network interfaces (run 'ip link' to list yours):"
read -rp "[?] Management / bettercap iface  [wlan0]:           " MGMT_IF
read -rp "[?] Responder / wired iface       [eth0]:            " WIRED_IF
read -rp "[?] Public IP for Turtle AutoSSH  [<YOUR_HEXBOX_PUBLIC_IP>]: " TURTLE_IP
read -rp "[?] MITM DNS redirect IP          [10.10.10.10]:     " MITM_IP

echo ""
echo "  Device passwords (press Enter to keep factory defaults):"
read -rp "[?] WiFi Pineapple pass           [hak5pineapple]:   " PINE_PASS
read -rp "[?] Shark Jack pass               [hak5shark]:       " SHARK_PASS
read -rp "[?] Packet Squirrel pass          [hak5squirrel]:    " SQ_PASS
read -rp "[?] LAN Turtle pass               [hak5turtle]:      " TURTLE_PASS
read -rp "[?] OMG Plug IP                   [192.168.1.50]:    " OMG_IP
read -rp "[?] OMG Plug pass                 [hak5omg]:         " OMG_PASS
read -rp "[?] Bash Bunny pass               [hak5bunny]:       " BUNNY_PASS
read -rp "[?] Flipper Zero serial port      [/dev/ttyACM0]:    " FLIPPER_PORT
read -rp "[?] BloodHound CE URL             [http://localhost:8080]: " BH_URL
read -rp "[?] BloodHound username           [admin]:           " BH_USER
read -rp "[?] BloodHound password           [BloodHound!]:     " BH_PASS
read -rp "[?] Kismet URL                    [http://localhost:2501]: " KISMET_URL
read -rp "[?] Kismet username               [kismet]:          " KISMET_USER
read -rp "[?] Kismet password               [kismet]:          " KISMET_PASS

echo ""
echo "  Covert exfil channels (leave blank to disable):"
read -rp "[?] DNS exfil domain              []:                " EXFIL_DNS_DOMAIN
read -rp "[?] DNS exfil server IP           [8.8.8.8]:         " EXFIL_DNS_SERVER
read -rp "[?] HTTPS exfil endpoint URL      []:                " EXFIL_HTTPS_URL
read -rp "[?] HTTPS exfil auth token        []:                " EXFIL_HTTPS_TOKEN
read -rp "[?] AES exfil key (32+ chars)     [change-me-to-32-byte-secret-key!]: " EXFIL_AES_KEY

HEXBOX_IP=${HEXBOX_IP:-10.0.0.99}
SCAN_NET=${SCAN_NET:-192.168.1.0/24}
C2_IP=${C2_IP:-YOUR.C2.IP.HERE}
MGMT_IF=${MGMT_IF:-wlan0}
WIRED_IF=${WIRED_IF:-eth0}
TURTLE_IP=${TURTLE_IP:-<YOUR_HEXBOX_PUBLIC_IP>}
MITM_IP=${MITM_IP:-10.10.10.10}
PINE_PASS=${PINE_PASS:-hak5pineapple}
SHARK_PASS=${SHARK_PASS:-hak5shark}
SQ_PASS=${SQ_PASS:-hak5squirrel}
TURTLE_PASS=${TURTLE_PASS:-hak5turtle}
OMG_IP=${OMG_IP:-192.168.1.50}
OMG_PASS=${OMG_PASS:-hak5omg}
BUNNY_PASS=${BUNNY_PASS:-hak5bunny}
FLIPPER_PORT=${FLIPPER_PORT:-/dev/ttyACM0}
BH_URL=${BH_URL:-http://localhost:8080}
BH_USER=${BH_USER:-admin}
BH_PASS=${BH_PASS:-BloodHound!}
KISMET_URL=${KISMET_URL:-http://localhost:2501}
KISMET_USER=${KISMET_USER:-kismet}
KISMET_PASS=${KISMET_PASS:-kismet}
EXFIL_DNS_DOMAIN=${EXFIL_DNS_DOMAIN:-}
EXFIL_DNS_SERVER=${EXFIL_DNS_SERVER:-8.8.8.8}
EXFIL_HTTPS_URL=${EXFIL_HTTPS_URL:-}
EXFIL_HTTPS_TOKEN=${EXFIL_HTTPS_TOKEN:-}
EXFIL_AES_KEY=${EXFIL_AES_KEY:-change-me-to-32-byte-secret-key!}

# ---- Write config.json via Python (avoids shell injection in passwords) ----
HEXBOX_CONFIG="$CONFIG" \
HEXBOX_IP="$HEXBOX_IP" SCAN_NET="$SCAN_NET" C2_IP="$C2_IP" \
MGMT_IF="$MGMT_IF" WIRED_IF="$WIRED_IF" \
PINE_PASS="$PINE_PASS" SHARK_PASS="$SHARK_PASS" SQ_PASS="$SQ_PASS" \
TURTLE_PASS="$TURTLE_PASS" OMG_IP="$OMG_IP" OMG_PASS="$OMG_PASS" \
BUNNY_PASS="$BUNNY_PASS" FLIPPER_PORT="$FLIPPER_PORT" \
BH_URL="$BH_URL" BH_USER="$BH_USER" BH_PASS="$BH_PASS" \
KISMET_URL="$KISMET_URL" KISMET_USER="$KISMET_USER" KISMET_PASS="$KISMET_PASS" \
EXFIL_DNS_DOMAIN="$EXFIL_DNS_DOMAIN" EXFIL_DNS_SERVER="$EXFIL_DNS_SERVER" \
EXFIL_HTTPS_URL="$EXFIL_HTTPS_URL" EXFIL_HTTPS_TOKEN="$EXFIL_HTTPS_TOKEN" \
EXFIL_AES_KEY="$EXFIL_AES_KEY" \
python3 - <<'PYEOF'
import json, os

e = os.environ.get
config = {
    "_comment": "HexBox configuration — generated by setup/configure.sh",
    "hexbox": {
        "ip":             e("HEXBOX_IP", "10.0.0.99"),
        "dashboard_port": 1337,
        "catcher_port":   8000,
        "http_port":      80,
        "loot_dir":       "~/hexbox/loot",
        "log_dir":        "~/hexbox/logs",
        "scan_target":    e("SCAN_NET", "192.168.1.0/24"),
    },
    "interfaces": {
        "management": e("MGMT_IF", "wlan0"),
        "responder":  e("WIRED_IF", "eth0"),
        "bettercap":  e("MGMT_IF", "wlan0"),
    },
    "devices": {
        "pineapple":      {"ip": "172.16.42.1", "user": "root", "pass": e("PINE_PASS",   "hak5pineapple"), "api_port": 1471},
        "sharkjack":      {"ip": "172.16.24.1", "user": "root", "pass": e("SHARK_PASS",  "hak5shark")},
        "packetsquirrel": {"ip": "172.16.32.1", "user": "root", "pass": e("SQ_PASS",     "hak5squirrel")},
        "lanturtle":      {"ip": "172.16.84.1", "user": "root", "pass": e("TURTLE_PASS", "hak5turtle")},
        "omgplug":        {"ip": e("OMG_IP", "192.168.1.50"), "user": "root", "pass": e("OMG_PASS", "hak5omg")},
        "bashbunny":      {"ip": "172.16.64.1", "user": "root", "pass": e("BUNNY_PASS",  "hak5bunny")},
    },
    "flipper": {
        "serial_port": e("FLIPPER_PORT", "/dev/ttyACM0"),
    },
    "bloodhound": {
        "url":      e("BH_URL",  "http://localhost:8080"),
        "username": e("BH_USER", "admin"),
        "password": e("BH_PASS", "BloodHound!"),
    },
    "sliver": {
        "host": "127.0.0.1",
        "port": 31337,
    },
    "c2": {
        "external_ip":   e("C2_IP", "YOUR.C2.IP.HERE"),
        "port":          443,
        "tor_enabled":   False,
        "vpn_interface": "tun0",
    },
    "kismet": {
        "url":      e("KISMET_URL",  "http://localhost:2501"),
        "username": e("KISMET_USER", "kismet"),
        "password": e("KISMET_PASS", "kismet"),
    },
    "exfil": {
        "dns_domain":      e("EXFIL_DNS_DOMAIN",  ""),
        "dns_server":      e("EXFIL_DNS_SERVER",   "8.8.8.8"),
        "https_url":       e("EXFIL_HTTPS_URL",    ""),
        "https_token":     e("EXFIL_HTTPS_TOKEN",  ""),
        "aes_key":         e("EXFIL_AES_KEY",      "change-me-to-32-byte-secret-key!"),
        "https_verify_tls": True,
    },
}
with open(os.environ["HEXBOX_CONFIG"], "w") as f:
    json.dump(config, f, indent=2)
print(f"[+] config.json written to {os.environ['HEXBOX_CONFIG']}")
PYEOF

# Restrict config.json permissions — it contains plaintext device passwords
chmod 600 "$CONFIG"
echo "[*] config.json permissions set to 600 (owner read/write only)"

# ---- Propagate attacker IP into payload files ----
OLD_IP="10.0.0.99"
if [ "$HEXBOX_IP" != "$OLD_IP" ]; then
    echo "[*] Updating payload IPs: $OLD_IP → $HEXBOX_IP"
    for f in "$PAYLOADS"/*.ducky "$PAYLOADS"/*.ps1 "$PAYLOADS"/*.sh; do
        [ -f "$f" ] || continue
        if grep -q "$OLD_IP" "$f" 2>/dev/null; then
            sed -i "s|$OLD_IP|$HEXBOX_IP|g" "$f"
            echo "    Updated: $(basename "$f")"
        fi
    done
else
    echo "[*] Payload IP unchanged (already $HEXBOX_IP)"
fi

# ---- Patch Turtle AutoSSH config placeholder ----
TURTLE_FOOTHOLD="$HEXBOX_DIR/payloads/turtle_foothold.sh"
if [ -f "$TURTLE_FOOTHOLD" ] && [ "$TURTLE_IP" != "<YOUR_HEXBOX_PUBLIC_IP>" ]; then
    sed -i "s|<YOUR_HEXBOX_PUBLIC_IP>|$TURTLE_IP|g" "$TURTLE_FOOTHOLD"
    echo "[*] Turtle foothold: SERVER set to $TURTLE_IP"
fi

# ---- Patch Squirrel MITM DNS redirect IP ----
SQUIRREL_MITM="$PAYLOADS/squirrel_mitm.sh"
if [ -f "$SQUIRREL_MITM" ] && [ "$MITM_IP" != "10.10.10.10" ]; then
    sed -i "s|10\.10\.10\.10|$MITM_IP|g" "$SQUIRREL_MITM"
    echo "[*] Squirrel MITM: DNS redirect IP set to $MITM_IP"
fi

echo ""
echo "[+] =================================================="
echo "[+]  Configuration complete."
echo "[+]"
echo "[+]  Next steps:"
echo "[+]    1. sudo python3 scripts/preflight.py   (validate everything)"
echo "[+]    2. bash scripts/engage.sh $SCAN_NET"
echo "[+]    3. Open http://$HEXBOX_IP:1337"
echo "[+] =================================================="
